export default[
    {
        key:1,
        name:"JOHN",
        image:require("../../../assets/LoginScreenImage1.jpg")
    },
    {
        key:2,
        name:"JOHN",
        image:require("../../../assets/LoginScreenImage1.jpg")
    },
    {
        key:3,
        name:"JOHN",
        image:require("../../../assets/LoginScreenImage1.jpg"),
    },
    {
        key:4,
        name:"JOHN",
        image:require("../../../assets/LoginScreenImage1.jpg"),
    },
    {
        key:5,
        name:"JOHN",
        image:require("../../../assets/LoginScreenImage1.jpg"),
    },
    {
        key:6,
        name:"JOHN",
        image:require("../../../assets/LoginScreenImage1.jpg"),
    },
    {
        key:7,
        name:"JOHN",
        image:require("../../../assets/LoginScreenImage1.jpg")
    },
]