export default[
    {
        key:1,
        class:"CrossFIT",
        image:require("../../../assets/LoginScreenImage1.jpg"),
        time:"8:00-9:00"
    },
    {
        key:2,
        time:"9:00-10:00",
        image:require("../../../assets/LoginScreenImage1.jpg")
    },
    {
        key:3,
        time:"10:00-11:00",
        class:"CrossFIT",
        image:require("../../../assets/LoginScreenImage1.jpg"),
    },
    {
        key:4,
        time:"11:00-12:00",
        class:"CrossFIT",
        image:require("../../../assets/LoginScreenImage1.jpg"),
    },
    {
        key:5,
        time:"13:00-14:00",
        class:"CrossFIT",
        image:require("../../../assets/LoginScreenImage1.jpg"),
    },
    {
        key:6,
        time:"14:00-15:00",
        class:"CrossFIT",
        image:require("../../../assets/LoginScreenImage1.jpg"),
    },
    {
        key:7,
        time:"15:00-16:00",
        class:"Open Gym",
        image:require("../../../assets/LoginScreenImage1.jpg")
    },
]